apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: gradle-docker
spec:
  containers:
    - name: gradle
      image: gradle:8.4.0-jdk21-alpine  # Gradle container for building the application
      command: [ "cat" ]
      tty: true
      volumeMounts:
        - name: workspace-volume
          mountPath: /workspace             # Mount for Jenkins workspace
    - name: docker
      command:
        - cat
      tty: true
      image: docker:latest                 # Docker container for building and pushing images
      securityContext:
        privileged: true                   # Required for using the host Docker daemon
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock  # Mount the host's Docker socket
        - name: docker-config
          mountPath: /etc/docker/daemon.json
          subPath: daemon.json
  volumes:
    - name: workspace-volume
      emptyDir: { }                         # Temporary volume for Jenkins workspace
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock         # Path to the Docker socket on the host
    - name: docker-config
      configMap:
        name: docker-config                # ConfigMap for Docker daemon configuration
